### PR TITLE
README.md: add nixpkgs link

### PR DESCRIPTION
**Pull request by Mic92**
Nix is a OS-independent package manager for Linux (in particular NixOS) and MacOS.

### CODE REVIEW

**Comment by kspearrin** [comment]
How was bitwarden submitted to this package manager?

**Comment by Mic92** [comment]
It's part of the file, which we use to semi-automatically update it from the npm:
https://github.com/NixOS/nixpkgs/blob/a1a3745fa9f921c2771e629e50339669f3a43d71/pkgs/development/node-packages/node-packages-v10.json#L5

The resulting package description can than found here:

https://raw.githubusercontent.com/NixOS/nixpkgs/a1a3745fa9f921c2771e629e50339669f3a43d71/pkgs/development/node-packages/node-packages-v10.nix

Our continuous integration system hydra build those.

**Comment by Mic92** [comment]
CLA signed!

**Comment by eliykat** [comment]
Hi @Mic92, the CLA isn't showing up as signed. If you'd still like to progress this PR, can you please look into this and try to sign it again. I'll then schedule it for further review.

**Comment by Mic92** [comment]
Look like this cla-assistant does not work at all. After redirecting me to this page it still shows the same status...
I give up on this.

**Pull request closed without merging**
